# Generated by Django 4.2.16 on 2024-10-15 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('faixa_salarial', models.CharField(choices=[('0-1000', 'Até 1.000'), ('1000-2000', 'De 1.000 a 2.000'), ('2000-3000', 'De 2.000 a 3.000'), ('3000+', 'Acima de 3.000')], max_length=20)),
                ('requerimentos', models.TextField()),
                ('ensino_minimo', models.CharField(choices=[('Fundamental', 'Ensino Fundamental'), ('Medio', 'Ensino Médio'), ('Tecnologo', 'Tecnólogo'), ('Superior', 'Ensino Superior'), ('Pós', 'Pós / MBA / Mestrado'), ('Doutorado', 'Doutorado')], max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_vagas', to='vagas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectativa_salarial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experiencia', models.TextField()),
                ('ensino_ultimo', models.CharField(choices=[('Fundamental', 'Ensino Fundamental'), ('Medio', 'Ensino Médio'), ('Tecnologo', 'Tecnólogo'), ('Superior', 'Ensino Superior'), ('Pós', 'Pós / MBA / Mestrado'), ('Doutorado', 'Doutorado')], max_length=20)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vagas.vaga')),
            ],
        ),
    ]
